abstract final class ShotOptions {
  static const sizes = [
    'Macro',
    'ECU',
    'BCU',
    'CU',
    'MCU',
    'MS',
    'Cowboy',
    'MLS',
    'FS',
    'LS',
    'ELS',
    'Establishing',
    'Master',
    'Single',
    'Two-shot',
    'Three-shot',
    'Group',
    'OTS',
    'POV',
    'Insert',
    'Cutaway',
  ];
  static const angles = [
    'Eye level',
    'Shoulder level',
    'Hip level',
    'Knee level',
    'Ground',
    'High',
    'Low',
    "Worm's-eye",
    "Bird's-eye",
    'Dutch',
    'Overhead',
    'Aerial',
    'Front',
    'Three-quarter front',
    'Profile',
    'Three-quarter rear',
    'Rear',
  ];
  static const movements = [
    'Static',
    'Pan',
    'Whip pan',
    'Tilt',
    'Roll',
    'Dolly',
    'Push in',
    'Pull out',
    'Dolly zoom',
    'Truck',
    'Pedestal',
    'Track',
    'Arc / orbit',
    'Slider',
    'Crane',
    'Jib',
    'Handheld',
    'Shoulder rig',
    'Steadicam',
    'Gimbal',
    'Drone',
    'Cable cam',
    'Vehicle mount',
    'Snorricam',
    'Zoom',
    'Crash zoom',
    'Rack focus',
  ];
  static const lenses = ['16mm', '24mm', '35mm', '50mm', '85mm', '70–200'];
  static const cameras = ['A-Cam', 'B-Cam', 'Drone'];
}
